daysUntilStale: 30
daysUntilClose: 30
exemptLabels:
  - pinned
  - security
staleLabel: wontfix
markComment: >
  Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
unmarkComment: false
closeComment: false