name: 'Terraform Infrastructure'

description: 'Setup and run Terraform for infrastructure'

inputs:
  project_id:
    description: 'GCP Project ID'
    required: true
  environment:
    description: 'Environment (dev/prod)'
    required: true
  region:
    description: 'GCP Region'
    required: false
    default: 'europe-west1'
  action:
    description: 'Terraform action (apply/destroy)'
    required: false
    default: 'apply'
  workload_identity_provider:
    description: 'GCP Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account'
    required: true
  terraform_version:
    description: 'Terraform version'
    required: false
    default: '1.14.1'

runs:
  using: "composite"
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3

    - name: Configure Environment
      shell: bash
      env:
        PROJECT_ID: ${{ inputs.project_id }}
        REGION: ${{ inputs.region }}
        ENVIRONMENT: ${{ inputs.environment }}
        ACTION: ${{ inputs.action }}
      run: |
        echo "PROJECT_ID=${PROJECT_ID}" >> $GITHUB_ENV
        echo "REGION=${REGION}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV
        echo "TF_STATE_BUCKET=tf-state-${PROJECT_ID}-${ENVIRONMENT}" >> $GITHUB_ENV
        echo "TF_LOCK_TIMEOUT=10m" >> $GITHUB_ENV
        
        if [[ "${ACTION}" == "destroy" ]]; then
          echo "DESTROY_FLAG=-destroy" >> $GITHUB_ENV
        else
          echo "DESTROY_FLAG=" >> $GITHUB_ENV
        fi

    - name: Verify State Bucket
      shell: bash
      run: |
        if ! gsutil ls -p $PROJECT_ID gs://$TF_STATE_BUCKET &> /dev/null; then
          echo "Creating Terraform state bucket gs://$TF_STATE_BUCKET..."
          gsutil mb --pap enforced -b on -p $PROJECT_ID -l $REGION gs://$TF_STATE_BUCKET
          sleep 10
        else
          echo "TF-state bucket gs://$TF_STATE_BUCKET already exists"
        fi

    - name: Terraform Format
      shell: bash
      run: terraform -chdir=terraform fmt -check -recursive -diff

    - name: Terraform Init
      shell: bash
      run: terraform -chdir=terraform init -backend-config="bucket=$TF_STATE_BUCKET"

    - name: Terraform Validate
      shell: bash
      run: terraform -chdir=terraform validate

    - name: Terraform Plan
      shell: bash
      run: |
        terraform -chdir=terraform plan \
          $DESTROY_FLAG \
          -lock-timeout=$TF_LOCK_TIMEOUT \
          -var-file="${ENVIRONMENT}.tfvars" \
          -input=false \
          -compact-warnings \
          -out=plan.tfplan

    - name: Terraform Apply
      shell: bash
      run: |
        terraform -chdir=terraform apply \
          -auto-approve \
          -lock-timeout=$TF_LOCK_TIMEOUT \
          -input=false \
          -compact-warnings \
          plan.tfplan

    - name: Terraform Output
      shell: bash
      if: inputs.action == 'apply'
      run: terraform -chdir=terraform output
